version: '3.3'

services:
  evictions_db_postgres:
    image: postgres:9.6.17
    restart: always
    environment:
      POSTGRES_USER: evictionsuser
      POSTGRES_PASSWORD: xbmKXrvNbdTYkokAtGySLNXNxesLGa4Ca6jRvXbflLhC8oyOHVEPCWStbmuGriD
      POSTGRES_DB: evictions
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080